### ISSUE TITLE
Change groupId and package domain

### ISSUE THREAD

**Issue by mimbrero** [migromarj/botica#6]
We don't own botica.com, so we should change the groupId and package domain to the format followed in other ISA projects.

This is practically mandatory, because this is likely to be published in Maven central, and one of their requirements is to own the domain used in groupId.

Also change in projects using BOTICA:
- [ ] isa-group/BOTICA-java-template#3
- [ ] isa-group/BOTICA-fishbowl#2
- [ ] isa-group/BOTICA-RESTest#2
