### ISSUE TITLE
Remove generate-templates

### ISSUE THREAD

**Issue by mimbrero** [migromarj/botica#7]
The generate-templates execution is unused at this point, there's documentation available for the configuration files in the wiki and there is a GitHub template to generate BOTICA projects.

Also remove from projects using BOTICA:
- [ ] isa-group/BOTICA-java-template#4
- [ ] isa-group/BOTICA-fishbowl#3
- [ ] isa-group/BOTICA-RESTest#3
